# DO NOT CHANGE THIS CI FILE WITHOUT DEVOPS APPROVAL, THIS HAS BEEN FINALIZED AS PER SECURITY GUIDELINES.
image: 618305041992.dkr.ecr.ap-south-1.amazonaws.com/freighttiger/thesource:kaniko-v1.0

stages:
  - check_valid_ticket_stage
  - secret_detection_stage
  - sonarqube_scan_stage
  - build_stage
  - trivy_image_scan_stage
  - deploy_dev_stage
  - deploy_qa_stage
  - auto_create_tag_stage
  - check_deployment_window_stage
  - deploy_prod_stage

variables:
  SONAR_PROJECT_KEY: "TO_BE_UPDATED"
  FEATURE_MAJOR: 'False'
  

include:
  - project: 'ft-neo/devops/gitlab-ci-templates'
    ref: main
    file: 
      - general/check_valid_ticket_template.yml
      - security/trivy-image-scan-template.yml
      - security/secret-detection-template.yml
      - security/sonarqube-scan-template-node20.yml
      - deployment/qa/deploy-qa-template.yml
      - deployment/dev/deploy-dev-template.yml
      - language-specific/node/node-20-build-template.yml
      - general/auto-create-gittag-template.yml
      - general/deploy_window_check_template.yml
      - deployment/production/deploy-prod-template.yml


check_valid_ticket:
  extends: .check_valid_ticket_job
  stage: check_valid_ticket_stage

secret_detection:
  extends: .secret_detection_job
  stage: secret_detection_stage

sonarqube_scan:
  extends: .sonarqube_scan_job
  stage: sonarqube_scan_stage

build:
  extends: .build_job
  stage: build_stage
  variables:
    DEV_ENV_NAME: dev

trivy_image_scan:
  extends: .trivy_image_scan_job
  stage: trivy_image_scan_stage

deploy_to_qa:
  extends: .deploy_qa_job
  stage: deploy_qa_stage

deploy_to_dev:
  extends: .deploy_dev_job
  stage: deploy_dev_stage

auto_create_tag:
  extends: .auto_create_tag_stage_job
  stage: auto_create_tag_stage

check_deployment_window:
  extends: .check_deployment_window_job
  stage: check_deployment_window_stage

deploy_to_prod:
  extends: .deploy_prod_job
  stage: deploy_prod_stage
